config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  resources :post_histories
  resources :posts
  resources :boards
  resources :user_roles
  resources :user_statuses
  resources :channel_groups
  resources :user_groups
  resources :channels
  resources :groups
  resources :sessions
  resources :users do
    collection{post :import}
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #setting homepage:
  #root to: "thing#otherthing"
  #         "callToController#callToMethod"
  root to: "channels#index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :sessions
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
      if user.role == "manager"
        can :manage, :all
      elsif user.role == "user"
        can :read, [Board, Channel, Post]
        can :create, Board
        can :create, Post
        can :create, User
        can :update, Board do |board|
          board.user == user
        end
        can :destroy, Board do |board|
          board.user == user
        end
        can :update, Post do |post|
          post.user == user
        end
        can :destroy, Post do |post|
          post.user == user
        end
        can :show, User do |i|
          i.id == user.id
        end
        can :update, User do |i|
          i.id == user.id
        end
      elsif user.role == "terminated"
        can :read, [Board, Channel, Post]
      else
        can :read, [Board, Channel, Post]
        can :create, User
      end

    #lower to higher permissions approach if we wanna do it this way
    # unless user
    #     can :read, :all
    #     can :create, :users
    #   else
    #     can :read, :all
    #     can :create, User
    #     can :create, Board
    #   if user.role == "manager"
    #     can :manange, :all
    #   end
    # end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :channel
  belongs_to :user
  has_many :posts, :dependent => :destroy

  def self.search(search)
    where("name ILIKE ?","%#{search}%")
  end

  # def current_permission
  #   @current_permission ||= Permission.new(current_user)
  # end
  # def authorize
  #   if current_permission.allow?
  #     redirect_to root_url, notice: "not authorized."
  #   end
  # end

end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :boards, :dependent => :destroy
  has_many :channel_groups
  has_many :groups, :through => :channel_groups

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/channel_group.rb
class ChannelGroup < ApplicationRecord
  belongs_to :channel
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :channel_groups
  has_many :channels, :through => :channel_groups
  has_many :user_groups
  has_many :users, :through => :user_groups

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
  belongs_to :user
  has_many :post_histories
 
  def self.search(search)
    where("name LIKE ? OR message LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/post_history.rb
class PostHistory < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post_histories
  has_many :posts, :dependent => :destroy
  has_many :boards, :dependent => :destroy
  has_many :user_statuses
  has_many :user_roles
  has_many :user_groups
  has_many :groups, :through => :user_groups
  has_secure_password
  validates :password,  :presence => :true,
                        :confirmation => true,
                        :length => {:within => 6..50}
  validates_uniqueness_of :username

  ROLES = %i[user manager terminated]

  #import csv
  require 'csv'
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user_hash = row.to_hash
      user = User.where(username: user_hash["username"])
      if user.count == 1
        user.first.update_attributes(user_hash)
      else
        User.create!(user_hash)
      end # end if statemnet
    end # end foreach
  end # end method

end

def formatted_name
  "#{fname} #{lname}"
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user 
end

app/models/user_status.rb
class UserStatus < ApplicationRecord
  belongs_to :user
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource #uses cancan here
  #under each method you can use cancan to restrict shit using following the syntax:
  #!authorize! :action, accessto
  # you can check/change these permissions in the ability.rb

  # GET /channels
  # GET /channels.json
  def index
      @channels = Channel.all
      if params[:search]
        @channels = Channel.search(params[:search]).order("created_at DESC")
      else
        @channels = Channel.all.order("created_at DESC")
      end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    authorize! :manage, @channel
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end
  # POST /channels
  # POST /channels.json
  def create
    authorize! :create, @channel
    @channel = Channel.new(channel_params)
    @channel.created_at = Time.now #set time as sysdate. but idk if we even gon use this
    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, flash: { success: 'Channel was successfully created.' }}
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    authorize! :update, @channel
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, flash: { info: 'Channel was successfully updated.' }}
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    authorize! :destroy, @channel
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, flash: { warning: 'Channel was successfully destroyed.' }}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Channel Name' %>
    <%= form.text_field :name, id: :channel_name %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-default"%>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<%= form_tag(channels_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Channels" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Channel</th>
      <th>Boards</th>
      <!--<th>Date</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= link_to channel.name, boards_url(:channel_id => channel.id)%></td>
        <td><%= channel.boards.count %> </td>
        <td><%#= channel.date %></td>
        <% if can? :manage, channel%>
        <td><%= link_to 'Show', channel %></td>
        <% end %>
        <% if can? :update, channel%>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <% end %>
        <% if can? :destroy, channel%>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= link_to 'Boards', boards_url(:channel_id => channel.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @channels.blank? %>
    <h4>There are no Channels containing the term <%= params[:search] %>.</h4>
<% end %>

<% if can? :create, Channel %>
<%= link_to 'New Channel', new_channel_path  , class: "btn btn-default" %>
<% end %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @channel.created_at.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%d at %H:%M") %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>