config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  resources :post_histories
  resources :posts
  resources :boards
  resources :user_roles
  resources :user_statuses
  resources :channel_groups
  resources :user_groups
  resources :channels
  resources :groups
  resources :sessions
  resources :users do
    collection{post :import}
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #setting homepage:
  #root to: "thing#otherthing"
  #         "callToController#callToMethod"
  root to: "channels#index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :sessions
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
      if user.role == "manager"
        can :manage, :all
      elsif user.role == "user"
        can :read, [Board, Channel, Post]
        can :create, Board
        can :create, Post
        can :create, User
        can :update, Board do |board|
          board.user == user
        end
        can :destroy, Board do |board|
          board.user == user
        end
        can :update, Post do |post|
          post.user == user
        end
        can :destroy, Post do |post|
          post.user == user
        end
        can :show, User do |i|
          i.id == user.id
        end
        can :update, User do |i|
          i.id == user.id
        end
      elsif user.role == "terminated"
        can :read, [Board, Channel, Post]
      else
        can :read, [Board, Channel, Post]
        can :create, User
      end

    #lower to higher permissions approach if we wanna do it this way
    # unless user
    #     can :read, :all
    #     can :create, :users
    #   else
    #     can :read, :all
    #     can :create, User
    #     can :create, Board
    #   if user.role == "manager"
    #     can :manange, :all
    #   end
    # end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :channel
  belongs_to :user
  has_many :posts, :dependent => :destroy

  def self.search(search)
    where("name ILIKE ?","%#{search}%")
  end

  # def current_permission
  #   @current_permission ||= Permission.new(current_user)
  # end
  # def authorize
  #   if current_permission.allow?
  #     redirect_to root_url, notice: "not authorized."
  #   end
  # end

end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :boards, :dependent => :destroy
  has_many :channel_groups
  has_many :groups, :through => :channel_groups

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/channel_group.rb
class ChannelGroup < ApplicationRecord
  belongs_to :channel
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :channel_groups
  has_many :channels, :through => :channel_groups
  has_many :user_groups
  has_many :users, :through => :user_groups

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
  belongs_to :user
  has_many :post_histories
 
  def self.search(search)
    where("name LIKE ? OR message LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/post_history.rb
class PostHistory < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post_histories
  has_many :posts, :dependent => :destroy
  has_many :boards, :dependent => :destroy
  has_many :user_statuses
  has_many :user_roles
  has_many :user_groups
  has_many :groups, :through => :user_groups
  has_secure_password
  validates :password,  :presence => :true,
                        :confirmation => true,
                        :length => {:within => 6..50}
  validates_uniqueness_of :username

  ROLES = %i[user manager terminated]

  #import csv
  require 'csv'
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user_hash = row.to_hash
      user = User.where(username: user_hash["username"])
      if user.count == 1
        user.first.update_attributes(user_hash)
      else
        User.create!(user_hash)
      end # end if statemnet
    end # end foreach
  end # end method

end

def formatted_name
  "#{fname} #{lname}"
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user 
end

app/models/user_status.rb
class UserStatus < ApplicationRecord
  belongs_to :user
end

app/controllers/post_histories_controller.rb
class PostHistoriesController < ApplicationController
  before_action :set_post_history, only: [:show, :edit, :update, :destroy]

  # GET /post_histories
  # GET /post_histories.json
  def index
    @post_histories = PostHistory.all
  end

  # GET /post_histories/1
  # GET /post_histories/1.json
  def show
  end

  # GET /post_histories/new
  def new
    @post_history = PostHistory.new
  end

  # GET /post_histories/1/edit
  def edit
  end

  # POST /post_histories
  # POST /post_histories.json
  def create
    @post_history = PostHistory.new(post_history_params)

    respond_to do |format|
      if @post_history.save
        format.html { redirect_to @post_history, notice: 'Post history was successfully created.' }
        format.json { render :show, status: :created, location: @post_history }
      else
        format.html { render :new }
        format.json { render json: @post_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_histories/1
  # PATCH/PUT /post_histories/1.json
  def update
    respond_to do |format|
      if @post_history.update(post_history_params)
        format.html { redirect_to @post_history, notice: 'Post history was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_history }
      else
        format.html { render :edit }
        format.json { render json: @post_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_histories/1
  # DELETE /post_histories/1.json
  def destroy
    @post_history.destroy
    respond_to do |format|
      format.html { redirect_to post_histories_url, notice: 'Post history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_history
      @post_history = PostHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_history_params
      params.require(:post_history).permit(:action, :date, :user_id, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/post_histories_helper.rb
module PostHistoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/post_histories/_form.html.erb
<%= form_with(model: post_history, local: true) do |form| %>
  <% if post_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_history.errors.count, "error") %> prohibited this post_history from being saved:</h2>

      <ul>
      <% post_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action, id: :post_history_action %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :post_history_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :formatted_name %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, id: :post_history_post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_histories/edit.html.erb
<h1>Editing Post History</h1>

<%= render 'form', post_history: @post_history %>

<%= link_to 'Show', @post_history %> |
<%= link_to 'Back', post_histories_path %>

app/views/post_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Histories</h1>

<table>
  <thead>
    <tr>
      <th>Action</th>
      <th>Date</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_histories.each do |post_history| %>
      <tr>
        <td><%= post_history.action %></td>
        <td><%= post_history.date %></td>
        <td><%= post_history.user.name %></td>
        <td><%= post_history.post_id %></td>
        <td><%= link_to 'Show', post_history %></td>
        <td><%= link_to 'Edit', edit_post_history_path(post_history) %></td>
        <td><%= link_to 'Destroy', post_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post History', new_post_history_path %>

app/views/post_histories/new.html.erb
<h1>New Post History</h1>

<%= render 'form', post_history: @post_history %>

<%= link_to 'Back', post_histories_path %>

app/views/post_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @post_history.action %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post_history.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @post_history.user.name %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_history.post_id %>
</p>

<%= link_to 'Edit', edit_post_history_path(@post_history) %> |
<%= link_to 'Back', post_histories_path %>