config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  resources :post_histories
  resources :posts
  resources :boards
  resources :user_roles
  resources :user_statuses
  resources :channel_groups
  resources :user_groups
  resources :channels
  resources :groups
  resources :sessions
  resources :users do
    collection{post :import}
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #setting homepage:
  #root to: "thing#otherthing"
  #         "callToController#callToMethod"
  root to: "channels#index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :sessions
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
      if user.role == "manager"
        can :manage, :all
      elsif user.role == "user"
        can :read, [Board, Channel, Post]
        can :create, Board
        can :create, Post
        can :create, User
        can :update, Board do |board|
          board.user == user
        end
        can :destroy, Board do |board|
          board.user == user
        end
        can :update, Post do |post|
          post.user == user
        end
        can :destroy, Post do |post|
          post.user == user
        end
        can :show, User do |i|
          i.id == user.id
        end
        can :update, User do |i|
          i.id == user.id
        end
      elsif user.role == "terminated"
        can :read, [Board, Channel, Post]
      else
        can :read, [Board, Channel, Post]
        can :create, User
      end

    #lower to higher permissions approach if we wanna do it this way
    # unless user
    #     can :read, :all
    #     can :create, :users
    #   else
    #     can :read, :all
    #     can :create, User
    #     can :create, Board
    #   if user.role == "manager"
    #     can :manange, :all
    #   end
    # end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :channel
  belongs_to :user
  has_many :posts, :dependent => :destroy

  def self.search(search)
    where("name ILIKE ?","%#{search}%")
  end

  # def current_permission
  #   @current_permission ||= Permission.new(current_user)
  # end
  # def authorize
  #   if current_permission.allow?
  #     redirect_to root_url, notice: "not authorized."
  #   end
  # end

end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :boards, :dependent => :destroy
  has_many :channel_groups
  has_many :groups, :through => :channel_groups

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/channel_group.rb
class ChannelGroup < ApplicationRecord
  belongs_to :channel
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :channel_groups
  has_many :channels, :through => :channel_groups
  has_many :user_groups
  has_many :users, :through => :user_groups

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
  belongs_to :user
  has_many :post_histories
 
  def self.search(search)
    where("name LIKE ? OR message LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/post_history.rb
class PostHistory < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post_histories
  has_many :posts, :dependent => :destroy
  has_many :boards, :dependent => :destroy
  has_many :user_statuses
  has_many :user_roles
  has_many :user_groups
  has_many :groups, :through => :user_groups
  has_secure_password
  validates :password,  :presence => :true,
                        :confirmation => true,
                        :length => {:within => 6..50}
  validates_uniqueness_of :username

  ROLES = %i[user manager terminated]

  #import csv
  require 'csv'
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user_hash = row.to_hash
      user = User.where(username: user_hash["username"])
      if user.count == 1
        user.first.update_attributes(user_hash)
      else
        User.create!(user_hash)
      end # end if statemnet
    end # end foreach
  end # end method

end

def formatted_name
  "#{fname} #{lname}"
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user 
end

app/models/user_status.rb
class UserStatus < ApplicationRecord
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Railsy Boi</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <!-- start navbar-->
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-right">
        <!-- add linkies here-->
          <li><%= link_to 'Home', root_url %></li>
          
          <!--if manager is logged in, can see users-->
          <% if can? :manager, User %>
          <li><%= link_to 'Users', users_path %></li>
          <% end %>
        
          <!-- start user drop down if logged in-->
          <% if current_user %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
                <li>
                  <%= link_to 'Log out of ' << current_user.username, logout_path %> 
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign up', signup_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
          <% end %>
          <!-- end if current user logged in else-->
        </ul>
      </nav>
    </div>
  </header>
  <!-- end navbar-->

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
  </body>
</html>